### ISSUE TITLE
Suggestion:  Enhanced Drone Behavior - Frigs

### ISSUE THREAD

**Issue by Smellyarmpits** [ISeeDEDPpl/Questor#104]
Is there anyway to have the Drone Torp/Autocannons perameter:

  
  <DontShootFrigatesWithSiegeorAutoCannons>false</DontShootFrigatesWithSiegeorAutoCannons>

modified/enhanced/added to allow for this behavior to occur within a minimum distance say 10 or 15kms?  This would allow questor to snipe off the frigs rushing at you and keep from using heavies at close range?

Thanks :-)

**Comment by ISeeDEDPpl** [comment]
describe what you mean by "this behavior" - you evidently misunderstand what that setting does. You will need to go into more detail on what you actually want it to do. 

"using heavies at close range" means what? heavy drones? dont use heavies at all, use lights. if I cant get a clear picture of what you want I cant possibly "fix" anything.

**Comment by Smellyarmpits** [comment]
Thank you for your reply.  What is meant here is to possibly create a setting that would allow a user to tell questor not to attack frigs and/or cruisers (user specify which or both) within 10kms (user specify distance) of the ship and possibly another that would force drones to attack anything within 10kms (user specify distance) over any other targets when they enter that distance (say 10kms specified).  Also, if a rat has been targeted and is being fired upon, when this new setting has been set, and enters the specified threshold (say 10kms user defined) questor will stop firing and switch to one that is outside the range.   I don't believe it would be necessary for this to apply to rat BS's since those can be hit at any distance.

I am asking this since a lot of level 4 mission are run by BS's and Large guns are crap within 10kms or more.  This would save a great deal in Ammo costs and capacitor use.  I also think it would increase survivability since questor won't be shooting at stuff it cant possibly hit in favor of targets it still can hit getting more of the incoming dps down and may have the side effect of increasing the speed at which missions are completed.

What do you think?

**Comment by ISeeDEDPpl** [comment]
I think in general it would be "better" to implement a 'timer' that is set when we change targets so that each "new target" starts a stopwatch. when the stopwatch hits the 'threshold' for that particular rat it switches off that target and onto the next... and incriments the threshold on the rat it switched off of to the next higher setting... 

so something like... target elite frigate with ID:12345... 60 seconds go by (the default threshold time) and the elite frigate with ID:12345 (our current target) is still alive. Increment the threshold time for that ID to 120 seconds... and  pick another target if available (anything but our current target, assuming the current target is not scrambling)

of course that is a bit of a simplification, but it would solve the "I cant hit that target" problem by literally moving onto the next target if the current target isn't dieing. ...and seems like it would solve more issues than it would cause, fixing some annoying corner cases atm.

**Comment by CasualBod** [comment]
if using a marauder ship (inherently very weak sensor strength, gets jammed easily) , wouldnt the above mechanic conflict in situations like "The Assault" mission where marauder would get nearly perma-jammed? Caldari missions like The Assault and Recon (1 of 3) do have heavy jamming on any ship, not just marauders, tho they are the ones most profitable. All i'm saying is, take jamming into consideration when(if) implementing this.

**Comment by ISeeDEDPpl** [comment]
for me this was solved with an even easier fix of orbiting frigates if that is our target thus reducing transversal... this doesn't help the poor souls using torps and no target painters but those people need a fit that works ffs. 

Re-ordering the targets may help their ship stay alive longer but ultimately torp ships will never be able to kill a frigate at close range w/o painters  (or take far far too long)
