### ISSUE TITLE
Out of ammo during mission

### ISSUE THREAD

**Issue by tetrikx** [ISeeDEDPpl/Questor#112]
If the ship gets out of ammo during a mission, it doesnt go automatically to base to refill ammo. The ship stays in space trying to reload ammo without succes.
To test this, set the required ammo less than enough to finish mission.
I am using the latest questor build.

**Comment by Irenicus1977** [comment]
Bot is not returning to station for more ammo. Here is the log.

23:51:39 [Combat] Activating weapon [1] on [Core High Admiral][ID: 9000000000000152776][5k away]
23:52:14 [Defense] Shields: [90%] Cap: [77%] Shield Booster: [1] activated
23:52:18 [Defense] Shields: [100%] Cap: [75%] Shield Booster: [1] deactivated [2] sec reactivation delay
23:52:55 [Drones] Recalling [ 5 ] drones because no NPC is targeting us within dronerange
23:53:12 [CombatMissionCtrl.ClearPocket] Targeting [Core High Admiral][ID: 9000000000000152775][47k away]
23:53:12 [CombatMissionCtrl.NavigateIntoRange] We are not approaching nor orbiting
23:53:12 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Core High Admiral][ID: 9000000000000152775]
23:53:13 [Combat] unlocking high value target [Core High Admiral][ID:9000000000000152776]{3} [50k away]
23:53:14 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:16 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:18 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:20 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:22 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:24 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:26 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:28 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:30 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:32 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:53:34 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]

**Comment by ISeeDEDPpl** [comment]
fixed in: 
https://github.com/ISeeDEDPpl/Questor/commit/965d5d77601703f19365ab035d3758dd7009ac7b

please confirm.

**Comment by Irenicus1977** [comment]
I have the same issue with the new fix. Ship is not returning to station. Here is the log:
21:52:21 [Combat] Activating weapon  [1] on [Core Commodore][ID: 9000000000000106367][6k away]
21:52:53 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [6]
21:52:55 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [6]
21:52:57 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [6]
21:52:59 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [6]
21:53:01 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [6]
21:53:03 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [6]

**Comment by ISeeDEDPpl** [comment]
hrm... k

**Comment by ISeeDEDPpl** [comment]
something is resetting the combatstate,,, hopefully the last commit just fixed it. If not Ill have to look at the questorUi code and see if its being reset there somehow.

**Comment by Irenicus1977** [comment]
I have issue but it is diffrent. Here is the log:
23:37:49 [Combat] unlocking high value target [Gist General][ID:9000000000000145793]{1} [19k away]
23:37:50 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
23:37:50 [Combat] ReloadNormalAmmo: We have ammo loaded that does not have a full reload available in the cargo.
23:37:51 [Combat] unlocking high value target [Gist General][ID:9000000000000145793]{1} [18k away]
23:37:52 [Combat] Activating weapon  [1] on [Angel Viper][ID: 9000000000000145790][19k away]
.......
23:42:57 [Combat] ReloadAll [1] with [Nova Heavy Missile][ typeID:206]
23:42:58 [CombatMissionCtrl.ClearPocket] Targeting [Gist Commander][ID: 9000000000000145787][74k away]
23:43:04 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:06 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:08 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:10 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:13 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:15 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:17 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:19 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:21 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]
23:43:23 [Combat] ReloadNormalAmmo: not enough [Explosive] ammo in cargohold: MinimumCharges: [6]

**Comment by ISeeDEDPpl** [comment]
This has been resolved in current experimental
