### ISSUE TITLE
Feature Request: Belt Ratting

### ISSUE THREAD

**Issue by Beechead** [ISeeDEDPpl/Questor#119]
Not sure if this is within the scope of desire for you or the DE team, but a belt ratting state would be nice that goes around to the various belts and kills the whole pocket. If a character with "x" standing comes into system have the bot panic and warp to station. Thank you!

**Comment by ISeeDEDPpl** [comment]
getting the basics of a belt ratting behavior written will be pretty straightforward and wont take up too much time, 
BUT it will clear belts, not chain them. It'll take some doing to get questor to know the difference between frigates, cruisers and battleships, ...easily, so that we can chain reliably.  

It is also really gonna need some new panic behavior where it'll cloak in a safespot instead of warping to station, which might be trouble in 0.0 w bubbles. We certainly need to disable the warping to any celestial when in panic... 

Any other corner cases I'm not thinking of?

**Comment by Beechead** [comment]
Yeah clearing the belts is good. I think warping to a safe would be ideal, but fitting the cloak could be a potential loss in isk/hr. perhaps setting it for a bookmark incase you have a POS or something?

It just needs to be able to panic quickly and perhaps align when in the belt? You could have it align to the safe while in belt and then it just realigns when traveling to the next belt?

**Comment by ISeeDEDPpl** [comment]
well, you definitely lose isk/hr when you get killed, lol. as long as their are multiple safespots to warp to when leaving the belt because youd need to be able to switch alignments if you got too close to an asteroid....  I'll start slowly working on this but I get the feeling this one is gonna take some doing to be polished enough to risk expensive ships/implants on.

**Comment by Beechead** [comment]
Id be willing to test with drake. Let me know any progress, I think this could be useful for making questor in general better.

**Comment by ISeeDEDPpl** [comment]
If 0.0 ratting is implemented it'll be an anomaly behavior first. closing this as it seems uninteresting compared to the alternatives and there is A LOT of ground work between there and here.
