### ISSUE TITLE
Objective done after DT

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#123]
If questor break mission because DT start but mission objective was done, questor try perform missions once again, despite the NPC not respawn ...

**Comment by ISeeDEDPpl** [comment]
This can possibly be fixed, but before we spend time/energy fixing this, what are we actually looking to resolve? We want to recover the time it takes to arm/undock/wtravel to bm, run through the actions one action every 10-20sec or so and return to base? .... or is their some deeper reason, like the bot hangs, doesnt have the right item or otherwise is currently getting stuck? The reason I ask is because if it is getting stuck we may need to resolve more than one bug when looking at this. 

I haven't run mine anywhere near downtime in awhile due to issues surrounding this... and had actually forgotten about it tbh.

**Comment by ISeeDEDPpl** [comment]
This should nw be resolved. AgentInteraction has been enhanced to pay more attention to the buttons available on the agent window and change the AgentInteraction purpose accordingly. This has been tested.
