### ISSUE TITLE
error in a storyline

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#143]
03:09:38 [Storyline] Going to do [Black Ops Crisis] for agent [XXXXXXXXXX] AgentID[XXXXXXXXXXXXXX]
03:09:39 [Arm] Opening Ship Hangar: waiting [3sec]
03:09:42 [Arm] Making [XXXX] active
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.

   at Questor.Storylines.GenericCourier.Arm(Storyline storyline) in
c:\Users\CORE\Desktop\ISeeDEDPpl-Questor-39d5f3e\ISeeDEDPpl-Questor-39d5f3e\Questor\Storylines\GenericCourierStoryline.cs:li
e 63

   at Questor.Storylines.Storyline.ProcessState() in
c:\Users\CORE\Desktop\ISeeDEDPpl-Questor-39d5f3e\ISeeDEDPpl-Questor-39d5f3e\Questor\Storylines\Storyline.cs:line 219

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Users\CORE\Desktop\ISeeDEDPpl-Questor-39d5f3e\ISeeDEDPpl-Questor-39d5f3e\Questor\Behaviors\CombatMissionsBehavior.cs:line
1289

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in
c:\Users\CORE\Desktop\ISeeDEDPpl-Questor-39d5f3e\ISeeDEDPpl-Questor-39d5f3e\Questor\Questor.cs:line 511

   at ..(DirectEve , Object , LSEventArgs )

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
03:09:52 [Arm.ActivateTransportShip] Done
03:09:53 [TravelerDestination.StationDestination] Destination set to [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
03:09:56 [Traveler] Setting destination to [XXXXXXXXXXXXXXX]

**Comment by ISeeDEDPpl** [comment]
Im not entirely sure what was causing this... 

if (Cache.Instance.DirectEve.ActiveShip.GivenName.ToLower() != transportshipName)

is the line causing the exception... we know that transportshipName didnt throw the exception because further up in that file:
string transportshipName = Settings.Instance.TransportShipName.ToLower();
and:
if (string.IsNullOrEmpty(transportshipName))
            {
                _States.CurrentArmState = ArmState.NotEnoughAmmo;
                Logging.Log("Arm.ActivateTransportShip", "Could not find transportshipName: " + transportshipName + " in settings!", Logging.orange);
                return StorylineState.BlacklistAgent;
            }

so the issue must be that our shipname that we are in occasionally does not return a value. I added a fix to experimental for this case.
