### ISSUE TITLE
add shuttle selection in ea 2/5

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#146]
add shuttle selection in ea 2/5

**Comment by grdk** [comment]
As I mentioned on IRC, we can already do this using this setting:
<transportShipName>ShipNameGoesHere</transportShipName>

This is also the current setting for your storyline courier hauler.

**Comment by Chryst** [comment]
Where we need write that ? Inside the mission code ?

If we have a transport ship in the transport slot in the xml, what happend when coem out the enemies abound 2/5 ? It go to that mission with the transport ship ?

**Comment by grdk** [comment]
No, it's a setting in Settings.xml

I see what happened with my last comment, the commenting system doesn't like markup language syntax. The setting is: < transportShipName > </ transportShipName >

It's been in there for a very long time, since the original EA 2/5 code was pulled from bbday's fork. The setting was repurposed a bit to also handle storyline couriers, so in short no to your second question. At the moment you cannot have a shuttle and a hauler (or more than 1 ship of any type for that matter) at once for the same setting.

**Comment by Chryst** [comment]
If i set the shuttle name in that slot i get stucked when it do the storyline missions require 8000 cargo container.

So here the only solution is put the name of the cargo ship with 8000+ space in that function < transportShipName > </ transportShipName >

**Comment by grdk** [comment]
Yes, correct. That's what I said in the previous comments ;-)

**Comment by Chryst** [comment]
But if in transport ship i use a cargo, it do the 2/5 with the cargo or with the shuttle ?

**Comment by Chryst** [comment]
Solved
