### ISSUE TITLE
Questor stopping for a strange reason

### ISSUE THREAD

**Issue by drpetarvojvodic** [ISeeDEDPpl/Questor#167]
I get a message in the middle of mission or agent interaction and than everything shuts down, every client on the same machine.
04:30:43 [Settings] WARNING! unable to find [C:\Program Files (x86)\InnerSpace.NET Programs.xml] loading default generic, and likely incorrect, settings: WARNING!

**Comment by Tokka72** [comment]
Had the same problem after i checked my internet connection. My Internet provider always disconnects and reconnects after 24 hours. After disconnect and reconnect the above mentioned problem occurred. Take a look in the logs of your Modem or whatever you are using to establish the connection.

**Comment by Chryst** [comment]
Yeah i have the same problem with the version of 2 days ago. Don't know if that is resolved with the last. Sometime happend that  error, and when the error happend the position of the logs are in the main folder so happend an error with the log position. Don't know if that problem is solved with the last version or no.

**Comment by ISeeDEDPpl** [comment]
This is not a questor issue (per se) that message literally means that questor is no longer logged into eve likely because you are disconnected. Questor restarts as it should. This issue is being closed as there is no bug on our end to fix.
