### ISSUE TITLE
Schedules

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#185]
I have a schedules.xml file that I believe is correctly set up.

Here is how it looks:

-<?xml version="1.0" encoding="utf-8" ?>
-Chars
  -char user="xxxxx" pw="xxxxx" name="xxx xxxx" start="08:00" stop="23:59" 
-/Chars

11:27:47 [Questor] Schedule: NOT setup correctly: stoptime  set to [10] hours from now at [9:27 PM]
11:27:47 [Questor] You can correct this by editing schedules.xml to have an entry for this toon
11:27:47 [Questor] Ex: <char user="" pw="MyPasswordForEVEHere" name="MyLoginNameForEVEHere" start="06:45"
stop="08:10" start2="09:05" stop2="14:20"/>
11:27:47 [Questor] make sure each toon has its own innerspace profile and specify the following startup program line:
11:27:47 [Questor] dotnet questor questor -x -c "MyEVECharacterName"

What am I doing wrong?

**Comment by Pluckyduck** [comment]
How are you starting up questor?  If you are using the IS profile then you would not be getting this notification.  It looks like you are manually logging in and then doing "dotnet questor questor".  I normally get this when i have manually logged guys in.

**Comment by Chryst** [comment]
Yes becouse if the stoptime is more long than 10 hours it quit in 10 hours.

**Comment by ISeeDEDPpl** [comment]
inside your innerspace profile you should have a command to start questor. it should look similar to:
`
dotnet questor questor -x -c "MyCharacterName"
`
which incidentally is exactly what it tells you in the quoted log. 
What command are you using to start questor?

FYI, this message is displayed because at this point Stoptime is not defined at all. Which means at the chantling scheduler is not being used. When this message is displayed Stoptime is defined as:
`
Cache.Instance.StopTime = DateTime.Now.AddHours(Time.Instance.QuestorScheduleNotUsed_Hours);
`
so that we wont immediately logoff / restart as soon as we startup =/ 
The _much_ better fix is to read the message it is giving you and fix the chantling scheduler so that you can define the times it logs in and out (up to 3 diff schedules per day)

FYI: it is also recommended to break up your schedule into 4-6 hour shifts so that you look a bit more human.

**Comment by I3Questor** [comment]
Awesome guys. Thanks for the assist, I have schedules working now.

ISDP, my internet connection is so crappy that I would be very lucky if I got 3 hours of non stop botting!
