### ISSUE TITLE
Dedicated salvager bugging when cargo gets full

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#189]
I always got the issue when the cargo of my dedicated salvager is almost full. He sends error and stop working. Don t even try to go back to base to unload stuff. Shows me this error always. 

  bei Questor.Modules.BackgroundTasks.Salvage.<LootWrecks>b__36(ItemCache wl) in
:\questor\Questor.Modules\BackgroundTasks\Salvage.cs:Zeile 481.

  bei System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)

  bei Questor.Modules.BackgroundTasks.Salvage.LootWrecks() in
:\questor\Questor.Modules\BackgroundTasks\Salvage.cs:Zeile 481.

  bei Questor.Modules.BackgroundTasks.Salvage.ProcessState() in
:\questor\Questor.Modules\BackgroundTasks\Salvage.cs:Zeile 684.

  bei Questor.Behaviors.DedicatedBookmarkSalvagerBehavior.ProcessState() in
:\questor\Questor\Behaviors\DedicatedBookmarkSalvagerBehavior.cs:Zeile 626.

  bei Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\questor\Questor\Questor.cs:Zeile 559.

  bei ..(DirectEve , Object , EventArgs )

  bei DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

  bei LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by Pluckyduck** [comment]
also had this issue.  It worked at first to return but i think that was because the salvager had finished cleaning all bookmarks that were older than 45 minutes.  After the point that a lot became older, it had run out of room twice and bugged out

**Comment by ISeeDEDPpl** [comment]
ok, yeah, this is a different cargo is full issue than the one I fixed a few weeks ago. This one involved the mission item which  of course doesnt exist with a dedicated salvager. 

fixed in current github. 
https://github.com/ISeeDEDPpl/Questor/commit/39ff82cd77ac831948b29f9ddcb19038c6505879

(storylines are bugged in current github though so you may want to wait to update or just pull this one commitm or disable storylines temporarily.)
