### ISSUE TITLE
Feature request: mail notification for war declaration

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#190]
Feature request: mail notification for war declaration

**Comment by ISeeDEDPpl** [comment]
afaik we have no capabilities within DE to know if we are at war or not. 

In order to get this info we would need to have the EVE API info and toon with the appropriate 'rights' and then we could query EVE mails or Notifications. We could then _possibly_ find the wardec evemail and turn it into an email. We do not yet use the EVEAPI for anything so this isnt likely to happen anytime soon.

This would be re-enventing the wheel though. There is already a web based service that does this and works fine. 
www.evenotify.com
