### ISSUE TITLE
Faction-specific xml loaded but not used

### ISSUE THREAD

**Issue by chantling** [ISeeDEDPpl/Questor#193]
Noticed that I was getting issues with some missions that have differently named targets for different factions, such as Unauthorized Military Presence (loot militants from Angel Cartel Personnel Transport Wreck, or Serpentis Personnel Transport Wreck, etc.).   Bot would cycle through all wrecks, and occasionally fail to loot the items.  Got some other weirdness too, like not using the correct damage type.  Did some digging.

Faction specific xmls are correctly loaded in AgentInteraction, which prints the mission name to the console.  However, missionxmlpath is redefined in Cache.cs, Arm.cs, and CombatMissionSettings.cs as well (why?) and only the mission name is used to locate the xml file.  By the time Questor's arming you, the generic mission damage type is used instead of the faction specific.  Worse, the generic mission actions are used; not terribly noticeable in most instances, but can be an issue as described above.  Not to mention inefficient when using the wrong damage types in these missions.

Solution is to correctly load the faction specific xml in each of the above instances.  I've done so and am playtesting.  If everything works properly I'll send the modified files to ISeeDEDPpl.

Better solution would be to check through the code to see if it's actually _necessary_ to redefine the missionxmlpath in all of the above locations, and if not, to simply use the settings cached from AgentInteraction.  I probably won't be doing this though, at least anytime soon.

**Comment by ISeeDEDPpl** [comment]
Ive created a common function to determine the missionXML path using the same criteria for arm and agentinteraction. It is necessary in both places because we do not know (for certain) that the bot will not be started in the arm state instead of going through the motions of doing agent interaction on startup (and likely other reasons but that was the 1st I had thought of)

unfortunately CombatMissionSettings.cs isn't yet actually used anywhere. it is cruft at this point. The original idea was the remove non-agentinteraction stuff from agentinteraction and into that file but it never was finished.

**Comment by ISeeDEDPpl** [comment]
FYI: https://github.com/ISeeDEDPpl/Questor/commit/028fab64b1a75ea6e0caa9ef6b194f13f1a6eecf

please test.

**Comment by ISeeDEDPpl** [comment]
Can anyone else confirm that this is fixed in current experimental?

**Comment by ISeeDEDPpl** [comment]
at this point I assume it is working. reopen if you find out otherwise.
