### ISSUE TITLE
Suggestion: Repair after every mission (for drones)

### ISSUE THREAD

**Issue by Karr** [ISeeDEDPpl/Questor#196]
It would save some drones if we had an option in the XML to turn on RepairAfterEveryMission

Just a thought

**Comment by ISeeDEDPpl** [comment]
Is the drone damage detection stuff not working reliably?

while in space is should be doing:
`
            foreach (EntityCache drone in Cache.Instance.ActiveDrones)
            {
                if (Settings.Instance.DebugDroneHealth) Logging.Log("Drones: GetDamagedDrones", "Health[" + drone.Health + "]" + "S[" + Math.Round(drone.ShieldPct,3) + "]" + "A[" + Math.Round(drone.ArmorPct,3) + "]" + "H[" + Math.Round(drone.StructurePct,3) + "][ID" + drone.Id + "]", Logging.white);
            }
            Cache.Instance.DamagedDrones = Cache.Instance.ActiveDrones.Where(d => d.Health < Settings.Instance.BelowThisHealthLevelRemoveFromDroneBay);
`
the setting above is misleading, since we added the repair it doesn't signify removing the drones from the dronebay, it signifies at what level of damage the drones will be considered damaged enough to need repair.

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/cceef845a45d4b5af25b8d396855c07c4d349a72
https://github.com/ISeeDEDPpl/Questor/commits/AlwaysRepairDrones
