### ISSUE TITLE
Feature Request: Sound notification

### ISSUE THREAD

**Issue by Serg1000** [ISeeDEDPpl/Questor#203]
whether it is possible to make so: what if who will write in a local chat worked a sound signal and in attempt to cause the personal message the sound signal too was published?

**Comment by ISeeDEDPpl** [comment]
this has already been requested, with slightly better english a few months ago. that issue is still open. feel free to help implement the feature. The ability to play sound is already part of questor we just need to write some routines to actually play the sound and call that routine when wanted. 

We probably want to create another background behavior that runs all the time no matter what the foreground behavior is doing... like cleanup and defense do. for now closing this as a duplicate.
