### ISSUE TITLE
Feature Request: Share ships through Corp Hangar

### ISSUE THREAD

**Issue by ollischulz123** [ISeeDEDPpl/Questor#236]
I was wondering whether it would be possible to implement a feature that lets one share a certain ship with a number of other characters that are in the same corp, i.e. recycle one ship instead of having to buy it for all characters. Corp Hangar access is working for dropping loot and taking Ammo. Would this be hard to implement? Thanks, amazing work!!

**Comment by Pluckyduck** [comment]
so what happens when two characters need the ship?

**Comment by ISeeDEDPpl** [comment]
short answer: no.
This needs to be thought out more before being proposed again. 
We would need to know in what scenario this is useful and what the questor instance would need to do if the ship wasnt available. 

What are we really talking about saving here? the need to only buy one noctus instead of X many? The benefits are near zero and the pain involved in making this "check in check out" system would be awful.

**Comment by ollischulz123** [comment]
I am using 4 different characters, which I am cycling throught the day/week to make things less obvious. Shiny pimped out ships are expensiv, so I was thinking I might just "hand over" the ship from one char to another through the corp hangar. In my case 2 characters would never need the same ship at once. I see the issue though with the checking system and the work that is involved. If it is just for my benefit it doesn't make sense to implement it anyways if others are not using it as well. Just thought of it to be a cool feature...

**Comment by Chryst** [comment]
That cause only conflicts... I think is really unuseful and cause only confusion and conflicts...
