### ISSUE TITLE
Unable to move ammo to ship

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#240]
01:04:23 [AgentInteraction] Loading mission xml [Worlds Collide] from [C:\Program Files (x86)\InnerSpace.NET Programs\Minmatar Missions 4 Level\Worlds Collide.xml]
01:04:24 [AgentInteraction] Mission [Worlds Collide] already accepted
01:04:24 [AgentInteraction] Closing conversation
01:04:28 [AgentInteraction] Attempting to close Agent Window
01:04:30 [AgentInteraction] Done
01:04:31 [Arm] Begin
01:04:31 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_StationItems', **********_)]
01:04:32 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_ShipCargo_**_********_', ***_***************)]
01:04:35 [Arm] Activating combat ship
01:04:37 [Arm] Opening Item Hangar: waiting [5sec]
01:04:43 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
01:04:43 [Arm] Opening Cargohold of active ship: waiting [4sec]
01:04:48 [Arm] Moving [5000] units of Ammo [Scourge Heavy Missile] from [ AmmoHangar ] to CargoHold
01:04:48 [Arm] Waiting for items
01:04:52 [Cleanup] Closing modal window...
01:04:52 [Cleanup] Content of modal window (HTML): [150,00 cargo units would be required to complete this operation. Destination container only has 0,00 units available.]

This problem apear only when questor starts and mission is already accepted. Sure there is enough space for ammo.

**Comment by Chryst** [comment]
I have just try and it work. Are you using the last version ? Seems not questor, but EVE bug.

**Comment by Pluckyduck** [comment]
got the same error hangs up in the same place, BTW, the cargohold was open and empty.

**Comment by ISeeDEDPpl** [comment]
I re-wrote the Arm and UnloadLoot routines yesterday
as of this commit: (and the 2 before it)
https://github.com/ISeeDEDPpl/Questor/commit/b3993b9c21a44d1b452c09f548f609aabe72b443

https://github.com/ISeeDEDPpl/Questor/commits/experimental

Ive been using it with 4 diff testing toons and havent been able to find a situation where it misbehaved... by all means let me know if you manage to find an issue. 

This issue is being closed though as it should no longer pertain to current experimental. 

please include consloe logs with 
`<debugUnloadLoot>true</debugUnloadLoot>`
and / or 
`<debugHangars>true</debugHangars>`

if you have trouble in arm or unloadloot

**Comment by ISeeDEDPpl** [comment]
There were a few issues with using the ItemsHangar as your LootHangar or AmmoHangar (as opposed to using the corp hangar) those are now fixed as well.
