### ISSUE TITLE
Sort wrecks by size

### ISSUE THREAD

**Issue by Tehtsuo** [ISeeDEDPpl/Questor#252]
I see the settings for blacklisting small and medium wrecks - would it be possible to just sort them instead?  I'd still like it to loot/salvage smalls, but I'd like it to prioritize large and mediums.

**Comment by Pluckyduck** [comment]
minus 1

**Comment by ISeeDEDPpl** [comment]
With a noctis this might be beneficial, although I am not sure why atm... because they usually do not run out of room.
With a battleship or T3 it seems like this would end up causing you to fly around more than usual, which would drastically increase looting times. 

If this makes logical sense and really would speed something up I am going to need to be lead through the reasons why and how... atm I am not seeing it. 

Out of sheer ignorance I am going to close this ticket. If someone can enlighten me we can implement this, I just do not want to add a feature that causes more harm than good.
