### ISSUE TITLE
Aligning to ____ so we might possibly hit [ target ]

### ISSUE THREAD

**Issue by thul** [ISeeDEDPpl/Questor#255]
Is there any way to turn this off? all i want is to have the bot burn in range and then just kill. I dont need it to keep in optimal (0.8 \* weapon range) (since im using missiles).

I have no setting that says it should try to maneuver into an position :S

**Comment by Chryst** [comment]
i think you need only set the speedtank off for have that.

**Comment by ISeeDEDPpl** [comment]
actually, having speed tank ON will help alleviate that.

I'll change it so that it only does the new behavior with turrets... (but I thought it might help with the crappy explosion velocity of torps too)

btw, it should only be doing that with non-speed tanked that are shooting frigates or speed tanked ships that are damn slow... I think I have it set to only align like that for ships that are going less than 300m/s

**Comment by thul** [comment]
well the problem is that when it does the "align" it actually moves away from my target. Using HM's i have a 100+ km range. For short range weapons it would be handy to move into range, i think you should make it so that it will move into range if you're out of range?

**Comment by ISeeDEDPpl** [comment]
thul, what ship are you flying that you are using heavy missiles and are not going more than 300m/s? drake?

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/bd32cfe93739926c00d5b71ddf0f25bf16519897

this could use some regression testing
