### ISSUE TITLE
storyline

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#264]
currier and material of war still not work. i try now

**Comment by ISeeDEDPpl** [comment]
anyone want to provide some logs? I can fix it faster if I do not have to wait for one of my toons to experience the issue. =/

**Comment by marivx** [comment]
10:34:53 [AgentInteraction] Found a window that needs 'yes' chosen...
10:34:53 [AgentInteraction] Content of modal window (HTML): [This mission involves objectives requiring a total
capacity of 9600,00 cargo units, but your active ship only has space for 10,00 more cargo units in its cargo hold.  Accept
anyway?]
10:34:57 [AgentInteraction] Attempting to close Agent Window
10:34:59 [AgentInteraction] Done
10:35:01 [AgentInteraction] Start Conversation [Complete Mission]
10:35:12 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
10:35:12 [AgentInteraction] Replying to agent
10:35:16 [AgentInteraction] Saying [Complete Mission]
10:35:16 [AgentInteraction] Closing conversation
10:35:24 [AgentInteraction] Attempting to close Agent Window
10:35:25 [AgentInteraction] Done

and stop here not go head
the proble is  not move the implant in the shuttle cargo.

If you move manual this implant on cargo the questor go head, when arrive in station not unload the loot

**Comment by Bubsan** [comment]
same problem here. but i noticed that somehow questor recovers after 70-ish minutes. don't know how, happened several times already. i don't do anything, i don't even notice problem because i'm away or something and when i come back i see next regular mission and time of that mission like 90-100 minutes and it's always when materials of war were run before. in the log 70 minutes were spend in station after materials of war.
if needed i can probably find and post my log.

**Comment by EchuI** [comment]
Q complete mission, closing conversation, but not move implants to cargohold and not return to base.
 storyline state  = bringspoilsofwar
 unload state     = idle
 traveler state    = at destination
agentinteraction = idle

**Comment by ISeeDEDPpl** [comment]
reported as working now.
