### ISSUE TITLE
Suggestion: Mission limit/Time limit and Shutdown 

### ISSUE THREAD

**Issue by Agorash** [ISeeDEDPpl/Questor#267]
First of all my apologizes for post this here, I has not found how to post in "Pull Request".
I really miss in Schedule tab an option to define from which hour Questor must stop "Autostart" or define how much missions I want it to do and then stop and shutdown entire PC. Some apps in my life do this kind of shutdowns thinking about people can't be paying attention on regular time. I will feel infinitely safer if I can demand to Questor to stop missioning from XX hour and it does :D Or define to do X missions and then stops or stops and shutdown my machine. I hope this don't sounds you crazy, like user I think this feature could be awesome. Thanks for your excellent work.

**Comment by ritl-de** [comment]
1. There is a Config File "Schedules.xml" where you can add start und stop time you must only start Questor with the following command to use it: dotnet questor questor -x -c "Charname"
2. You can create a Windows Task to Shutdown your PC at a given Time
3. Stop Questor after x Mission is a unnecessary feature as you can define a Stop Time

**Comment by ISeeDEDPpl** [comment]
yes, as prophetal says we already have a scheduling feature that you are not using. 

We DO have the code in questor to allow for "quit after x missions" instead of "Stop at y time" but I have not taken the time to plug that code into the settings XML stuff. Keep this issue open and I'll add it this weekend. It was not a high priority because so many people prefer to use the time based scheduling rather than the x # of missions per session method, but like I said the backend code it already there so I might as well finish adding it.  

FYI, you can also specify an arbritray OS command when shutting down questor that could do whatever you wanted it to do.

`
<CloseQuestorArbitraryOSCmd>false</CloseQuestorArbitraryOSCmd> 
<CloseQuestorOSCmdContents></CloseQuestorOSCmdContents> 
`
I would guess that most ppl do not use that though. Most would just let questor shutdown normally and have another scheduled task in windows to handle shutting down the PC if that is what they wanted to do.
