### ISSUE TITLE
Issue: Questor targets and kills grey merchants in Dread Pirate Scarlet

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#29]
I dont think this is supposed to happen.

**Comment by ISeeDEDPpl** [comment]
Are you sure they aren't regular NPCs? 

I don't use clearpocket in dread pirate scarlet so I haven't noticed this. 

It would definitely be nice to have a list of all NPCs encountered (killed?!) and all their details.
I may introduce something like that to compliment the pocket stats, but it is going to be a 'project' more than likely as I want it to include all LCOs all NPCs and possibly their distances to each other 
(so that we could build a spatially accurate (to a point) model of where things are for that mission.)

**Comment by ghost** [comment]
16:57:41 MissionController: Finished Action.MoveToBackground [target: Acceleration Gate]
16:57:41 MissionController: Starting Action.ClearWithinWeaponsRangeOnly
16:57:42 MissionController.ClearwithinWeaponsRange: Targeting [Merchant][ID: 9000000000000951574][42k away]
16:57:54 MissionController.ClearwithinWeaponsRange: Targeting [Merchant][ID: 9000000000000951573][40k away]
16:58:01 Combat: Activating painter [1005961714186] on [Merchant][ID: 9000000000000951574][40k away]
16:58:01 Combat: Changing [1005839350440] with [Scourge Javelin Torpedo][TypeID: 24529]
16:58:03 Combat: Activating painter [1005961712848] on [Merchant][ID: 9000000000000951574][39k away]
16:58:04 Questor: Wallet Balance Has Not Changed in [ 3 ] minutes.
16:58:13 Combat: Activating weapon [1005839350440] on [Merchant][ID: 9000000000000951573][38k away]

**Comment by ghost** [comment]
Fixed.
