### ISSUE TITLE
Dedicated Salvager BleedingEdge not using gates

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#324]
If usegate true or false, the dedicated salvager will not go into missions.  
log snipet below:

[DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base

**Comment by Pluckyduck** [comment]
i have been looking over the code and only could find 1 part that related to the dedicated salvager.

Q\Behaviors\DedicatedBookmarkSalvagerBehavior.cs line 498 to 525

On line 500 "if (Cache.Instance.GateInGrid())" returns true then it will always return to base.  i can not find any part that that would cause it not to care if the gate is there. I can not find the code part that looks that at the settings file to see if  we have selected to go into missions or not.

**Comment by Pluckyduck** [comment]
i think if i add the Cache.Instance.GateInGrid && Settings.Instance.useGatesInSalvage to it, it should see the gate and if the setting file is false....

**Comment by ISeeDEDPpl** [comment]
after looking over the code and thinking about it a bit this is desired behavior for the dedicated salvager. The alternative to this would be a salvage boat (which normally has no repairer or resists) would be entering 'live' missions which shouldn't not be necessary and is not desirable for the salvage boat. So long as we salvage the wrecks before the 2 hour timer is up then the salvager has done its job, there is no reason to risk entering a mission that is ongoing. Once the mission has been turned in the gates will disappear and the salvager will salvage all the wrecks at those bookmarks. If their is a flaw in the above logic please explain that flaw.

**Comment by Pluckyduck** [comment]
This was going off what you had said you did.  From my understanding, from what you had said (ISDP), questor will still go into panic mode if getting attacked.  Also, i have it set up to kill all rats to include sentries, so when the salvager is heading to the bookmark, the room is empty.
  If this is not how it is suppose to be working let me know.  I am getting a lot more GE/AE missions since grey list is working again and they take a while to do (i might have to go back and re-optimize them now).

**Comment by ISeeDEDPpl** [comment]
dedicated salvager is not the after mission salvager. from your comments you seem to have the 2 confused. 

Dedicated salvager will salvage at corp bookmarks, including in progress mission bookmarks, thus the not wanting to follow gates and end up in a pocket that is actively being cleared (remember NPC aggro now switches on a dime)

After mission salvaging switches ships in station after the mission is complete and goes back to the bookmarks that same toon created. By definition the after mission salvager should only be returning to the salvage bookmarks after the mission has been completed and turned in. There should never be any gates or NPCs, unless, there is someone in your mission (never really understoond the mechanics of when eve cares that you have soeone in a deadspace so it wont despawn and when it doesnt care and despawns anyway... but anyway). the after mission salvager has some more logic (that I purposely ripped out of the dedicated salvager) to follow gates anyway, since we KNOW FOR CERTAIN that all the pockets in the mission XML have been processed (and should be clear if you mission XML is not fubar). The same can not be said for the dedicated bookmark salvage mode

**Comment by Pluckyduck** [comment]
as requested the log is in pastebin for the ease of reading.

http://pastebin.com/1mH6eQXA

 if i pause Q and manually warp to the next bookmark, it picks right back up.  When Q finishes the current BM it will go back to the oldest BM, if the oldest BM still has a gate it gets stuck again and starts spamming.  I manually moved it twice and on the third clean up, the gate was gone on the BM location that Q first encountered  the gate. 

If you need more of a log, please let me know.

**Comment by ISeeDEDPpl** [comment]
bleedginedge should now skip bookmarks within an AU of  the in progress mission and proceed to process other salvage bookmarks if possible
