### ISSUE TITLE
CourierMission exception when changing to transportship

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#338]
So far with Operation Doorstep and Materials for War, was in the journal but Q did not see them.  Shipyard Theft was seen and seems to be working fine.

 [Storyline] Currently have  [0] missions available
 [Storyline] Currently have  [0] storyline missions available
 [Storyline] Currently have  [0] storyline missions questor knows how to do
 [Storyline] Currently have  [0] storyline missions questor knows how to do and are not blacklisted

 [Storyline] Currently have [1] missions available
 [Storyline] Currently have [1] storyline missions available
 [Storyline] Currently have [1] storyline missions questor knows how to do
 [Storyline] Currently have [1] storyline missions questor knows how to do and are not blacklisted
 [CombatMissionsBehavior] Storyline detected, doing storyline.

**Comment by Pluckyduck** [comment]
I think found part of the problem, one was nothing to buy in the station and second was that an exception had occurred  when trying to activate transport ship.  more test will be completed tomorrow.

**Comment by drokk99** [comment]
I get that exception the first time it tries to get in my transport ship every session, it throws an exception, blacklists the agent, but still gets in the ship. If I have a courier storyline in the journal and start Q while in my transport it works fine.

**Comment by ISeeDEDPpl** [comment]
can I get a log of that exception? "log nameofmylogfilehere.log" will log everything including exceptions to the text file you specify.

**Comment by drokk99** [comment]
This is what I get.

23:14:33 o[yStorylineo] yCurrently have  [1] missions available
23:14:33 o[yStorylineo] yCurrently have  [1] storyline missions available
23:14:33 o[yStorylineo] yCurrently have  [1] storyline missions questor knows how to do
23:14:33 o[yStorylineo] yCurrently have  [1] storyline missions questor knows how to do and are not blacklisted
23:14:33 o[yCombatMissionsBehavioro] wStoryline detected, doing storyline.
23:14:34 o[yStorylineo] yCurrently have  [1] missions available
23:14:34 o[yStorylineo] yCurrently have  [1] storyline missions available
23:14:34 o[yStorylineo] yCurrently have  [1] storyline missions questor knows how to do
23:14:34 o[yStorylineo] yCurrently have  [1] storyline missions questor knows how to do and are not blacklisted
23:14:34 o[yStorylineo] yGoing to do [Hunting Black Dog] for agent [xxxxxxx] AgentID[xxxxxxx]
23:14:35 o[yArmo] wMaking [xxxxxx] active
23:14:36 o[yGenericCourierStorylineo] wException thrown while attempting to switch to transport ship:Object reference not set to an instance of an object.
23:14:36 o[yGenericCourierStorylineo] wblacklisting this storyline agent for this session because we could not switch to the configured transportship named [xxxxxx]
23:14:37 o[yStorylineo] oBlacklistAgent: The agent that provided us with this storyline mission has been added to the session blacklist

It actually does get into the transport ship, and will switch ships correctly from then on during that session.
If the session is started whilst in the transport ship it all works fine.

**Comment by ISeeDEDPpl** [comment]
please test current bleedingedge, this MIGHT be fixed.

**Comment by drokk99** [comment]
first attempt using https://github.com/ISeeDEDPpl/Questor/commit/b902a2781e1053b895f928533e414fd6d7162834 worked as intended, will get back to you again after a few couriers come up.
