### ISSUE TITLE
Q ignores the lootHangar

### ISSUE THREAD

**Issue by EchuI** [ISeeDEDPpl/Questor#343]
Q ignores the lootHangar and unload loot in a personal hangar rather than corporate hangar

```
18:10:42 [CombatMissionsBehavior.TravelHome] Arrived at destination
18:10:43 [CombatMissionsBehavior.TravelHome] Arrived at destination
18:10:44 [CombatMissionsBehavior] UnloadLoot: Begin
18:11:00 [UnloadLoot.MoveAmmo] Moving [28] Mission Completion items to ItemHangar
18:11:01 [UnloadLoot.MoveAmmo] will Continue in [ 1 ] sec
18:11:03 [UnloadLoot.MoveAmmo] Stacking Corporate Ammo Hangar
18:11:05 [Cache.StackLootHangar] Stacking Corporate Loot Hangar: waiting [4sec]
```

**Comment by ISeeDEDPpl** [comment]
my guess is that you are running an older (not current) broken revision.

18:11:00 [UnloadLoot.MoveAmmo] Moving [28] Mission Completion items to ItemHangar
... means that while trying to move the "mission completion items" (i.e. items that are commonly required to complete missions (like militants, etc)) it moved 28 diff items instead of a smaller more reasonable number. AND the log shows no other loot moved, so I have to believe you are running a rev from a few days ago that mistakenly lumped all loot into that category. This has since been fixed in experimental.

**Comment by EchuI** [comment]
Yes, you are right, I had a version of the 25th of February
