### ISSUE TITLE
Primary weapons attacking web frig

### ISSUE THREAD

**Issue by grio43** [ISeeDEDPpl/Questor#367]
addWebifiersToPrimaryWeaponsPriorityTargetList>false</addWebifiersToPrimaryWeaponsPriorityTargetList

with 
speedTank>true</speedTank
Primary weapons still try to shoot the webber frig.
ofc they all miss.

It overrides frig op range/ distance/frig speed

**Comment by grio43** [comment]
it seems to be rare to happen. Not all the time currently
Also a current issue is if drones get killed they don't get relaunched.

**Comment by kn0xv1lle** [comment]
This is because speed tank is true when speed tank is true youre primary weapons will always shoot the web frig. I mentioned to change this.

**Comment by ISeeDEDPpl** [comment]
kn0xv1lle, it has been changed. 

Grio, I'll need logs, potentially with
`<debuggetBestTarget>true</debuggetBestTarget>`
in your characters settings xml to see WHY it is being chosen as a primary weapons target

**Comment by grio43** [comment]
Way to get around that? I still want it to orbit at closer ranges but its a
BS it can tank the dps. It does damage out at 65km but does more when its
closer.

**Comment by grio43** [comment]
I got a feature request. Always have the tank running upon undocking and
moving between stargates option somewhere. Would help when people try to
gank you.

**Comment by grio43** [comment]
Wouldnt want to perma run the shield booster/armor rep that drain the cap
if your not running a stable setup but would make things harder to gank.

**Comment by ISeeDEDPpl** [comment]
Why would you think that? in high sec your only going to have about 15ish seconds to gank before concord comes and owns everything that is blinky. 

So... while yes you gain something if you are armor repping and you always rep at the end of the cycle and thus MIGHT pickup 2-4 seconds more rep then you otherwise would have... 

A better idea would be to have a different rep threshold when you are not in a mission (Cache.Instance.InMission = false) Then you could rep as soon as you get ANY damage. We could also trigger reps when we have ANY of the invasion stuff in panic triggered I suppose. I'm not sure how much it would actually help though tbh. In most situations where you get ganked they do so in 1 or 2 volleys. It is pretty easy to get overkill enough to overcome your booster when you are killed in two volleys =) Does anyone want to work the math on this before I invest time in it?

**Comment by grio43** [comment]
Most gankers go with heavy voly ships like the t3 mimiatrar ship. They will
catch you on a gate and blow you up there. Have someone with a bump ship
waiting to bump you. Their volies tend to be about 8k a voly with a t1
fittied ship. A golem sits around 40kish EHP with its hardners on. I did
look closer today hardners are always on but the issue seems. Dunno maybe
it could if targeted by play turn shield booster on.

**Comment by ISeeDEDPpl** [comment]
well, if we did it by just pvp targeting you'd end up with frigates targeting you in missions running down you cap (not funny, but very funny at the same time)

**Comment by grio43** [comment]
Can it be limited to ship type? People only really gank in a few hulls.

**Comment by Pluckyduck** [comment]
if the pros want to gank you, not a damn thing you can do but log off and not back on for a while.  when i say "pros" i mean the ones that actually bring the hammer when they find you.  most of us have seen the 1 and 2 guys that just dont know what they are doing, For most of the non-pros, fitting a damage control mod will drastically help you so having a dev spend a massive amount of time on something that has a very little chance of helping does not make a lot of sense.
