### ISSUE TITLE
Panic and no station in local

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#379]
So maybe its a wrong setting on my site because i didn t set panic safespots but if questor panic and there are no safespot bookmarks it just make this. And don t go to sun like it always did when there was no station.

19:47:38 [Panic] No station found in local?
Exception during event execution: System.ArgumentNullException: Value cannot be null.

Parameter name: source

   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)

   at Questor.Modules.BackgroundTasks.Panic.ProcessState() in
c:\Users\Michael\Desktop\Questor-BleedingEdge\Questor.Modules\BackgroundTasks\Panic.cs:line 487

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Users\Michael\Desktop\Questor-BleedingEdge\Questor\Behaviors\CombatMissionsBehavior.cs:line 245

   at Questor.Questor.EVEOnFrame(Object sender, EventArgs e) in c:\Users\Michael\Desktop\Questor-BleedingEdge\Questor\Questor.cs:line
613

Is there a need of bookmarks ? Well if yes this is a big pain because i dont want to check every system to make a bookmark for every single character. Just let it warp to the sun like always. 
If i have to make bookmarks what should it look like ? Just a Corp Bookmark with name safespot ? Or a personal bookmark ? I am very confused on this.

**Comment by ISeeDEDPpl** [comment]
no, they aren't required. it was just a bug. squished. 
It should now behave normally. If you have safespot bookmarks it will use them otherwise it will go to the sun. (we could really randomize that a bit more too tbh)

https://github.com/ISeeDEDPpl/Questor/commit/fa28b74914982b613ef5e6318f9b1fbb73998765

Either personal or corp, doesnt matter. It is pre-defined as any bookmark starting with the word "safespot" but you can change that in your characters settings xml: 

`<!-- All safespot bookmarks will be prefixed by this string, default: safespot: -->`
`<safeSpotBookmarkPrefix>safespot</safeSpotBookmarkPrefix><!-- default is safespot: -->`

**Comment by kn0xv1lle** [comment]
Thanks for fixing. Great work everytime. Well now i know why i lost some ships ;) But yeah every fixed bug is good.
