### ISSUE TITLE
Drones not attacking frigs. New logs debugGetBestTarget==true

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#382]
http://pastebin.com/89z4D3aC

**Comment by Pluckyduck** [comment]
at point did you start to see it split.....at least with in 1 to 2 minutes and what did you primary weapons shoot while the drones were not?  this would help decode the log.

**Comment by oldmeat** [comment]
I do not know if I understood well ...
In this log my primary weapons attack frigates which webbyfing me, drones attack bs ignoring all frigates.
Even when i have changed setup file and i set options about PrimaryWeapons to ignoring all ECM ships,
my primary weapons still attack this frigate.

**Comment by ISeeDEDPpl** [comment]
yeah, that frigate was not showing up as a frigate. "IsNPCFrigate" didnt have that one in the list. I hacked it in for now. 

There was another bug with "current target" being kept even against wrong sized targets (when a frigate is the last thing left its ok that primary weapons shoot it, but when their is a respawn they should switch targets. Same with drones with big stuff, that is fine until a frigate shows up then they should switch)

The above is now fixed in bleedingedge afaik. THANK YOU for the logs!
