### ISSUE TITLE
The latest Bleeding Edge, client hang up

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#386]
In the latest build Bleeding Edge:
b0fc899d976bc26f0e76ff30f59e2011181bf35a

Always about 10min client is freeze and hangup.
logs ends on this line:

Combat] Targeting primary weapon priority target [Dire Pithum Eraser][ID: [truncatedID]97357][33k away] potentialHighValueTargets.Count [10]

and in other tests usually:
[Combat] Targeting .....

**Comment by ISeeDEDPpl** [comment]
try: https://github.com/ISeeDEDPpl/Questor/commit/94f86977b67bc9c2ea660e4bd118aed985750f90

The issue is not jumping out and biting me at this point. If that commit doesn't resolve it Ill need logserver logs with some details as to what is throwing an "error" in the logserver. We have to be doing something twice in a frame, or doing something that doesn't make sense (unlocking something that isn't locked, etc). 

At this point both debugTargetCombatants and debugGetBestTarget would possibly be useful (and then again might be worthless), both of them on is going to spam your log quite a bit though.

**Comment by oldmeat** [comment]
94f8697 the same
I send logs to your email, sorry for that but it too little time gap to safe public release ...

**Comment by ISeeDEDPpl** [comment]
Unfortunately the log was not useful. I've increased the Targeting Delay which may help a bit, and fixed a few more bugs having to do with target selection.

**Comment by Status12** [comment]
still freezing

**Comment by kn0xv1lle** [comment]
Yep confirming this

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/12e9a3560bda58aff35bb464b0630f2a7f9667f1

**Comment by ISeeDEDPpl** [comment]
freezing fixed.

**Comment by kn0xv1lle** [comment]
Still a problem. QUestor warps into combat tries to target enemies and hangs up.

**Comment by Pluckyduck** [comment]
simple testing on mine was that it would just rotate through the targets with unlocking and locking.  will generate a log this morning. to support....looking for any new debugging true statement first.

**Comment by Pluckyduck** [comment]
http://pastebin.com/JhQbJaZa

log

**Comment by oldmeat** [comment]
Please comment/update in next Issue:
https://github.com/ISeeDEDPpl/Questor/issues/391
