### ISSUE TITLE
Now drones again attack BS and ignoring frigate

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#411]
In the latest BE 735d6901b136b8e4ac6389b2e56f0efaff0d39e8 drones again attack BS and ignoring frigate and primary weapon shoot to frigate.

[Combat] Targeting high value target [Angel Viper][ID: [truncatedID]55640][32k away] highValueTargets.Count
...

Angel Viper is not high value target only frigate

**Comment by ISeeDEDPpl** [comment]
this was multiple things... and should now be fixed in bleedingedge. Please re-open with new logs if you manage to trigger this again. If you DO trigger this make sure you have entries in your ShipTargetValues.xml for the NPCs having trouble. (I do not think we are missing any in that file at this point though)
