### ISSUE TITLE
BleedingEdge ( 4d88e3f9cd494 )targeting Customs Commissioner while heading to and from mission

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#418]
This is the log that is heading to the mission. i do not have any debugging turn on, this is in with all false.

12:14:40 [Traveler] Setting destination to [system]
12:15:03 [Traveler] Warping to [system][15.56 AU away]
12:15:44 [CombatMissionsBehavior.GotoMission] Priority targets found, engaging!
12:15:44 [Traveler] Jumping to [Maurasi]
12:15:45 [CombatMissionsBehavior.GotoMission] Priority targets found, engaging!
12:15:45 [Combat] Targeting non-aggressed NPC target [Caldari Customs Commissioner][ID: [truncatedID]00016][2k away]
12:15:46 [CombatMissionsBehavior.GotoMission] Priority targets found, engaging!
12:15:46 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
12:15:46 [GetBestTarget: none] Could not determine a suitable target
12:15:47 [CombatMissionsBehavior.GotoMission] Priority targets found, engaging!
12:15:48 [CombatMissionsBehavior.GotoMission] Priority targets found, engaging!
12:15:48 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
12:15:48 [GetBestTarget: none] Could not determine a suitable target
12:15:49 [CombatMissionsBehavior.GotoMission] Priority targets found, engaging!
12:15:49 [EntityCache.LockTarget] [TargetCombatants.TargetThisNotYetAggressiveNPC] tried to lock [Caldari Customs Commissioner][1.94k][[truncatedID]00016][0] targets already, can retarget in [16]
12:16:06 [CombatMissionsBehavior.GotoMission] Priority targets found, engaging!

**Comment by ISeeDEDPpl** [comment]
very odd. 

try latest bleedingedge: 7baca3916168b417fa0593a76502661af4e94e80
https://github.com/ISeeDEDPpl/Questor/commit/7baca3916168b417fa0593a76502661af4e94e80

**Comment by Pluckyduck** [comment]
will try it today when i get back home, what version of DE are you running, the one with it or the last one?

**Comment by molasar** [comment]
I'm quite sure that its still going on with the https://github.com/ISeeDEDPpl/Questor/commit/7baca3916168b417fa0593a76502661af4e94e80 .  Also in mission Silence The Informant questor has poroblems when there are multiple webbers. Basically it keeps dropping targets and regretting them. There are like 6 or so webbers there so its a bit of unusuall mission. My point is it shouldn't ever drop targeted webber frig.  There seems to be also problem in damsel in distress mission  . When questor has break on attackers parameter set when killing "Kruul's Pleasure Gardens". Basically it breaks when next wave of agrro show up but hen keeps retargeting  and dropping pleasure gardens without shooting at anything. Ill post some logs when i find them

**Comment by molasar** [comment]
11:39:36 [CombatMissionCtrl.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]] Unlocking [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away] due to kill order being put on hold
11:39:38 [Defense] Shields: [96%] Cap: [69%] Shield Booster: [1] deactivated [2] sec reactivation delay
11:39:38 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget failed (unknown reason)
11:39:38 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget failed: target was not in Entities List
11:39:38 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget aborted: target is already being targeted
11:39:38 [Combat] Targeting high value target [Seven Assassin][ID: [truncatedID]12758][22k away] highValueTargets.Count [2]
11:39:38 [Combat] Targeting high value target [Seven Assassin][ID: [truncatedID]12757][22k away] highValueTargets.Count [2]
11:39:40 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Zor to make room for [PreferredPrimaryWeaponTarget]
11:39:42 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Seven Assassin to make room for [PreferredPrimaryWeaponTarget]
11:39:43 [Defense] Shields: [94%] Cap: [68%] Shield Booster: [1] activated
11:39:44 [Combat] Targeting preferred primary weapon target [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away]
11:39:47 [Defense] Shields: [96%] Cap: [68%] Shield Booster: [1] deactivated [2] sec reactivation delay
11:39:48 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Kruul's Pleasure Gardens to make room for [OutOfRange or Ignored]
11:39:48 [CombatMissionCtrl.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]] Unlocking [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away] due to kill order being put on hold
11:39:50 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget failed (unknown reason)
11:39:50 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget failed: target was not in Entities List
11:39:50 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget aborted: target is already being targeted
11:39:50 [Combat] Targeting high value target [Seven Assassin][ID: [truncatedID]12756][30k away] highValueTargets.Count [2]
11:39:50 [Combat] Targeting high value target [Zor][ID: [truncatedID]12759][33k away] highValueTargets.Count [2]
11:39:52 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Seven Assassin to make room for [PreferredPrimaryWeaponTarget]
11:39:54 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Zor to make room for [PreferredPrimaryWeaponTarget]
11:39:56 [Defense] Shields: [94%] Cap: [68%] Shield Booster: [1] activated
11:39:56 [Combat] Targeting preferred primary weapon target [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away]
11:39:59 [Defense] Shields: [95%] Cap: [68%] Shield Booster: [1] deactivated [2] sec reactivation delay
11:39:59 [Combat] Reloading [1] with [Inferno Heavy Missile][90][TypeID: 208]
11:39:59 [CombatMissionCtrl.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]] Unlocking [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away] due to kill order being put on hold
11:40:00 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget failed (unknown reason)
11:40:00 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget failed: target was not in Entities List
11:40:00 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget aborted: target is already being targeted
11:40:00 [Combat] Targeting high value target [Seven Assassin][ID: [truncatedID]12757][23k away] highValueTargets.Count [2]
11:40:00 [Combat] Targeting high value target [Zor][ID: [truncatedID]12759][32k away] highValueTargets.Count [2]
11:40:02 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Seven Assassin to make room for [PreferredPrimaryWeaponTarget]
11:40:04 [Defense] Shields: [94%] Cap: [69%] Shield Booster: [1] activated
11:40:04 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Zor to make room for [PreferredPrimaryWeaponTarget]
11:40:06 [Combat] Targeting preferred primary weapon target [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away]
11:40:07 [Defense] Shields: [96%] Cap: [67%] Shield Booster: [1] deactivated [2] sec reactivation delay
11:40:08 [Combat] Targeting low value target [Seven Death Dealer][ID: [truncatedID]12761][12k away] lowValueTargets.Count [1]
11:40:08 [Combat] Targeting low value target [Seven Death Dealer][ID: [truncatedID]12754][18k away] lowValueTargets.Count [1]
11:40:10 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Kruul's Pleasure Gardens to make room for [OutOfRange or Ignored]
11:40:10 [CombatMissionCtrl.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]] Unlocking [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away] due to kill order being put on hold
11:40:12 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Seven Death Dealer to make room for [HighValueTarget]
11:40:14 [Combat] Targeting preferred primary weapon target [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away]
11:40:16 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Seven Death Dealer to make room for [PreferredPrimaryWeaponTarget]
11:40:17 [Defense] Shields: [94%] Cap: [70%] Shield Booster: [1] activated
11:40:19 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Kruul's Pleasure Gardens to make room for [OutOfRange or Ignored]
11:40:19 [CombatMissionCtrl.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]] Unlocking [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away] due to kill order being put on hold
11:40:20 [Defense] Shields: [96%] Cap: [67%] Shield Booster: [1] deactivated [2] sec reactivation delay
11:40:21 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget failed (unknown reason)
11:40:21 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget failed: target was not in Entities List
11:40:21 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Kruul's Pleasure Gardens][20,3k][[truncatedID]68634][3] targets already, LockTarget aborted: target is already being targeted
11:40:21 [Combat] Targeting high value target [Seven Assassin][ID: [truncatedID]12756][30k away] highValueTargets.Count [2]
11:40:21 [Combat] Targeting high value target [Zor][ID: [truncatedID]12759][30k away] highValueTargets.Count [2]
11:40:23 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Seven Assassin to make room for [PreferredPrimaryWeaponTarget]
11:40:25 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Seven Assassin to make room for [PreferredPrimaryWeaponTarget]
11:40:27 [Combat] Targeting preferred primary weapon target [Kruul's Pleasure Gardens][ID: [truncatedID]68634][20k away]

Thats what basically happens in Damsel in distress mission

**Comment by Pluckyduck** [comment]
updated and still doing the following

12:31:40 [TravelerDestination.StationDestination] Destination set to [station]
12:31:45 [Traveler] Setting destination to [system]
12:31:47 [Traveler] Warping to [Perimeter][7.82 AU away]
12:31:49 [Combat] Reloading [1] with [Scourge Light Missile][25][TypeID: 210]
12:32:29 [Combat] Targeting non-aggressed NPC target [Caldari Customs Commissioner][GroupID: 446][TypeID: 19367][ID: [truncatedID]00013][6k away]
12:32:29 [Traveler] Jumping to [Perimeter]
12:32:30 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
12:32:30 [GetBestTarget: none] Could not determine a suitable target
12:32:32 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
12:32:32 [GetBestTarget: none] Could not determine a suitable target
12:32:33 [EntityCache.LockTarget] [TargetCombatants.TargetThisNotYetAggressiveNPC] tried to lock [Caldari Customs Commissioner][7.13k][[truncatedID]00013][0] targets already, can retarget in [16]
12:32:34 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
12:32:34 [GetBestTarget: none] Could not determine a suitable target
12:32:51 [TravelerDestination.StationDestination] Warp to and dock at [station][15.56 AU away]

**Comment by juandrito** [comment]
I have the same problem.

**Comment by KingMike** [comment]
same problem here

**Comment by ISeeDEDPpl** [comment]
this should be fixed in bleedingedge.
