### ISSUE TITLE
courier mission fix

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#424]
Pot and Kettle - Making Amends (5 of 5)  needs to be added to AgentInteraction.cs to match up with CourierMissionCtrl.cs

**Comment by frbyles** [comment]
Well i added this mission to mine but took it back out and blacklisted it since it can be either combat or courier. and i dont want to loose my transport ship or try to haul shit with my machariel . i would like to test it though but ill have to wait until i get that chain of missions and acctually catch them in progress

**Comment by drokk99** [comment]
The encounter version is called Pot and Kettle - To Battle (5 of 5)  so q should be able to tell them apart.

sorry for the long time in responding, it took this long for me to get the encounter one, always seem to get low sec for the 4th one and when you decline you get the courier 5th.
