### ISSUE TITLE
Targetting issue

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#482]
In the latest exp: 4500d670eba15bc671462a91c34960dc5247ff12

In lvl3 mission, i dont have bs only frigate and cruisers.
Bot target some frigs and cruisers but shoot first to frigates.
I put some logs later.

**Comment by ISeeDEDPpl** [comment]
hrm, not a great way to fix that w/o adjusting

minimumTargetValueToConsiderTargetAHighValueTarget
and/or
maximumTargetValueToConsiderTargetALowValueTarget
The values are listed in Output\ShipTargetValues.xml
By default both cruisers and frigates are considered lowvalue targets iirc. 
because of this we assume drones kill frigates faster and frigates are more dangerous (scramblers, etc) so as a low value target it makes sense to have them killed smallest first... if the above settings do not produce the desired behavior I can look at adjusting the targetcombatants/getbesttarget routines.
