### ISSUE TITLE
[feature request] cancel storyline courier missions and missions to low-seс

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#49]
Is it possible to add a feature cancel storyline courier missions and missions to low-seс?

**Comment by ISeeDEDPpl** [comment]
As far as I am aware their is no DE function to remove storyline missions. Internally they use a different "remove / decline" function than regular missions. I'll look into it again and see If I can dig anything up. This has been a low priority for me because manually clearing these only needs to be done once every week or two...

**Comment by ISeeDEDPpl** [comment]
maybe once the bounty system goes up a DE dev will enlighten us...

**Comment by ISeeDEDPpl** [comment]
this has been completed iirc.
