### ISSUE TITLE
Change target loop

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#532]
In the commit 1317119639a2fa4f78ebe48336257c0b3e48251a
When i do mission and appear 2 the same (the same name) small ECM ships then Q target one of this and aggro drones and missile bays on him, few sec later change aggro drones and missile bays to second ECM ship who is called just as first. And again and again. 
I have only GetBestTarget for drones in logs, but missiles work the same and change target the same time as drones.
http://privatepaste.com/dfec6885ea

**Comment by CasualBod** [comment]
I confirm that this is indeed an issue. It has been occurring for a while now (at very least in past 10 commits or so). My tengu AB speedtanked is sometimes just ignoring or indefinitely switching targets between actively ECM'ing frigs (be it webbing or scrambling). I couldn't point the exact culprit if the issue because it was not persistent. Settings are set: speedtank, small ship priority 5 (all available targets) big ship priority 0, web frigs ecm type is set to priority, other ecm types turned off, but it does not seem to make a difference.

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in bleedingedge. we now track the last target we were shooting while in the same pocket and try to re-target it if needed and stay on the same target, within reason... if their are still bugs related to this I will need new logs.
