### ISSUE TITLE
(Request) if we cant find something on lootitem action

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#552]
if we cant find something on the lootitem action, make it not search the rest of the wrecks.  ninja looters are a bastard =?   having a battleship run around all over range to find something that is not there, is totally not cool.

BTW @ISeeDEDPpl  we miss you.

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge.
THIS IS A MAJOR CHANGE!
lootitem will now move on to the next action after all the containers defined by the target parameter have been looted (or are missing). lootitem will no longer loot the field! if you want to specifically stop and loot the field use a loot action after (or instead of?) the lootitem action.
