### ISSUE TITLE
DeniedActivateTargetNotPresent Exceptions

### ISSUE THREAD

**Issue by duketwo** [ISeeDEDPpl/Questor#557]
Getting this exception after each rat kill. Using the recent version.
Can someone confirm?

(44ms to the eve server / no packet loss.)

eve/client/script/ui/inflight/shipModuleButton\shipmodulebutton.py(1512) ActivateEffect
newException = UserError('DeniedActivateTargetNotPresent',)

**Comment by Pluckyduck** [comment]
i get it a lot

**Comment by ISeeDEDPpl** [comment]
we will get that a lot less once we can predict which volley will kill and not try til activate mods on that terget (instead shoot other targets if available) after 2-3 seconds of that guestimate. If still alive after that delay send another volley at the nearly dead target. 

I'll be working on that soon.

**Comment by Pluckyduck** [comment]
on this one, would it make sense to check to see if it  is still on grid or would that cause to much cpu processinng to do?

**Comment by duketwo** [comment]
can't think of a way to do it, checking the entitiy for !HasExploded && !HasReleased doesn't help at all. is guessing the only way to determine this?

**Comment by Pluckyduck** [comment]
i know we have a way of logging what is on grid but does it make sense to see if the target is still on grid before activating again?  pease correct me if i am wrong, but the gun will stop firing when target is not locked, because we are jammed, out of range or sensor dampened to the point we cant lock. So before actiavting, should be do a search to see if it is on grid?

**Comment by ISeeDEDPpl** [comment]
the issue is that the EVE clients info is out of date. It will tell you the entity is there and yet the server thinks it is not. IIRC. We already check to make sure the entity is on grid, has not exploded, etc. Its a timing issue. Keep in mind that questor only polls game data every x milliseconds, so we DO miss events from the client about entities exploding/releasing etc. We cant really poll the game every millisecond and hope we catch those events (too laggy!)

It does however cleanly clear up the issue if we aren't shooting at things that "should be dead soon"...

**Comment by ISeeDEDPpl** [comment]
To clarify a bit, its an issue that should only effect missiles (and any other delayed damage weapon),,, you shoot, the ammo travels through space and only later hits the target killing it. If you fire your weapons again as the previous volley kills it you get this message (keep in mind their is probably a 1 sec overlap here). So really, we do not have to know when the NPC is going to die (although that is calculatable atm). We really just need to know the flight time of your weapons to that target and not shoot at them again within 2 sec of another volley actually hitting them (that is probably pretty rare with the cycle times being what they are).

**Comment by duketwo** [comment]
sounds good, lets just make sure we dont loose any or too much dps while doing this

**Comment by ISeeDEDPpl** [comment]
this should no longer occur. please try to replicate with latest bleedingedge.
