### ISSUE TITLE
Targetting issue

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#570]
Q lock and unlock targets very many times when fight:

http://privatepaste.com/d9c0537170

**Comment by ISeeDEDPpl** [comment]
are you sure that is current bleedingedge? 
the logging there does not match up with what is in github at the moment.

**Comment by ISeeDEDPpl** [comment]
There are only 6 places in questor that we unlock things, 3 of them are in salvage.cs and only unlock wrecks.
1 is part of the "Kill" action when dealing with the breakOnAttackers option
Logging.Log("CombatMissionCtrl[" + PocketNumber + "]." + _pocketActions[_currentAction], "Unlocking [" + KillTargetEntity.Name + "][" + KillTargetEntity.MaskedId + "][" + Math.Round(KillTargetEntity.Distance / 1000, 0) + "k away] due to kill order being put on hold", Logging.Teal);

the other 2 are unlocking either HighValueTargets or LowValueTargets as needed: 
Logging.Log("Combat [TargetCombatants]" + module, "Unlocking LowValue " + unlockThisLowValueTarget.Name + "[" + Math.Round(unlockThisLowValueTarget.Distance / 1000, 0) + "k] myTargtingRange:[" + Combat.MaxTargetRange + "] myWeaponRange[:" + Cache.Instance.WeaponRange + "] to make room for [" + reason + "]", Logging.Orange);

the logging you linked does not exist at all in current bleedingedge (and the spacing is wrong enough that I can tell you the tree you are using is quite old (1+year?) or was never part of my bleedingedge)

**Comment by oldmeat** [comment]
Sorry, you have right ... i not replace my old build with the latest.
