### ISSUE TITLE
Questor window not showing

### ISSUE THREAD

**Issue by Blinker** [ISeeDEDPpl/Questor#8]
Not sure if this is unique with your build but since the build on the 15th my Questor windows rarely show. Sometimes when I start questor it loads up sometimes it doesnt, questor still carries on working though no window.

**Comment by ISeeDEDPpl** [comment]
http://isboxer.com/forum/viewtopic.php?p=8703

The window issue is an innerspace problem that started when eve implemented the new launcher. If you launch /bin/exefile.exe instead of eve.exe you will get the questor window every time. 

You may want to add these command line arguments as well: /noconsole /noBreakpadUpload

let me know if this does not solve the problem for you. It would be great if we could get Lax to update innerspace to not need this particular change, but I am not certain that it is possible considering the eve launcher changes.

**Comment by Blinker** [comment]
Thanks bud, works lovely.
