### ISSUE TITLE
Bug: Dedicated Salvager Still Broke!

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#81]
Still broke

**Comment by ISeeDEDPpl** [comment]
can I get a better description than that? I do not have a toon that can easily run this... if I can get decent bug reports it'll be fixed otherwise it will not. 

I was able to salvage 5 BMs in local, 5 next door and then return home ok. Where is the problem? If the bookmarks aren't refreshing, they are supposed to refresh every 6 min while docked..., then try opening people and places (manually) and see if that helps. If it does let me know. 

If that isn't the issue, please describe what the issue is and include console logs where possible.

**Comment by ghost** [comment]
I would, I do not test this part of the script. I put in the issue... asked the person that was complaining about the issue to comment on the issue and he didn't. Time for me to get mad at him.
