### ISSUE TITLE
Drones bug

### ISSUE THREAD

**Issue by tetrikx** [ISeeDEDPpl/Questor#84]
Hi, there is something wrong with panic/drone behaviour in the last build

I just lost a battleship...the strangest log entry:

xx:46:31 Panic: Start panicking, capacitor [2%] below [5%]
xx:46:31 Combat: Targeting low  value target [Dire Pithi Infiltrator][ID:9000000000000607185]{2} [3k away]
xx:46:31 EntityCache: LockTarget is ignored for [Dire Pithi Infiltrator][9000000000000607185], can retarget in [8]
xx:46:31 Drones: Recalling [ 5 ] drones because we are done with this pocket.
xx:46:33 Panic: We are still warp scrambled!

So the drones were out while the ship got scrambled but they got recalled by this trigger: 
xx:46:31 Drones: Recalling [ 5 ] drones because we are done with this pocket.
I dont know why the drones got recalled, the pocket wasnt finished...its strange.
The drones didnt come out anymore so the battleship got destroyed. 

Could you please take another look in the drone part of the build?

If you need more explanation or log entries, dont hesitate to ask.

**Comment by tetrikx** [comment]
Maybe adding a warpscrambled check in every recall if bracket in drones.cs would solve this?
Like for example if (!Recall && Check && !Cache.Instance.TargetedBy.Any(t => t.IsWarpScramblingMe)) ? Would this work?

**Comment by ISeeDEDPpl** [comment]
the drones.cs works like thus:
1) If drones arent out: list reasons to put them out (being scrambled is at the top of the list, so we always put out drone if scrambled)
2) if drones are out: list reasons to pull them in
a) if our ship isnt being targeted by any NPCs
b) if we processed a 'done' mission XML action and we aren't currently scrambled
c) if our drones are taking shield damage
d) if our drones are taking armor damage
e) if our drones are taking hull damage
f) if we actually lost a drone

keep in mind that if we do pull the drones because of damage and we are scrambled they should be thrown right back out, hopefully without NPC aggro. In the above "b" is what changed 3 hours ago. Before that change any done action would mean pulling the drones in regardless of anything else. 

I don't really see a reason to keep the drones out while they are taking damage. We can possibly ignore shield damage arguably.. but a drone taking armor damage is just going to die... and soon. 

https://github.com/ISeeDEDPpl/Questor/commit/f7d1e4acaa8a621f96bc566e918746ca261371c7

**Comment by tetrikx** [comment]
Thanks. Tested the fix and its ok now. Closing.
