### ISSUE TITLE
Starting InnerSpace EvE DEFAULT profile and then Questor crashes instance.

### ISSUE THREAD

**Issue by Karr** [ISeeDEDPpl/Questor#85]
Eve Default profile is the generic Eve with no character XML's defined.

If you start a basic default profile and then load questor, the instance closes.  If you open questor BEFORE you log in the screen is blank.

This used to work fine, to where you could use TRAVELER feature on alt toons.

I copied an XML and named it to the toon.. and all works fine. (Temp Fix)

**Comment by ISeeDEDPpl** [comment]
no, that isn't the temp fix, that is the 'right way'. 

How do you expect questor to work without loading any settings? If I understand you correctly you want to be able to load questor WITHOUT a character XML yes? We can possibly fix this to work (badly) but Im not sure why anyone would want to... copying the XML insures that things like the "home" station are set so that you can use gotobase. We _can_ set sane defaults for everything and not need the XML, but it will still mean setting things 'wrong' like the home station (which we'd have to set to Amarr, Rens, or Jita... or something...)

That being said if you are trying to start another questor related utility that may or may not require a settings XML as well now... which we can set defaults for and potentially not require an XML, but again its a matter of having those defaults make sense

**Comment by ISeeDEDPpl** [comment]
The issue I guess is that somehow questor is crashing (badly) rather than gracefully telling you that you did something naughty... I'll look into it, but making questor.exe work (well) without am XML at all will likely not be resolved soon. The crashing issue though is something that should not happen.

**Comment by Karr** [comment]
Like I said...it is for the traveler feature only.  On toons I would never use to grind.  Like.. hey alt... bring me some AMMO... or hey.. I need 4x ravens from Jita.. oh...btw.. get back to jita.. nice little alt ;)

Not a big deal.. I copied one of my xmls and traveler (which is broke :P) came up.  Always a work around.

**Comment by asmodeus655** [comment]
Why not use questormanager instead? It doesn't requires any settings and a sequence of actions can be set. Quite comfortable.

**Comment by ISeeDEDPpl** [comment]
This wasnt as big of a pain in the ass as I thought it would be. I'll have something committed tomorrow after some more testing. Questor will be MUCH more tolerant of not having a character settings XML. 

Its 95% done already, it just needs polish. I am not certain how you had this working before though, I had to make some fairly significant changes to get this far.

**Comment by ghost** [comment]
make sure the eveonline default profile points to ccp\bin\exefile.exe

i bet it isnt!

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/6123f96818e186d648f3213b5ec65e65238fa79e

this should be, at least mostly fixed. 
questor no longer crashes on startup without a settings file.

**Comment by Karr** [comment]
Yeah, seen that!  Awsome job.  Now if only the traveler feature would be available :P  Thanks for the fix ISee ;)
