### ISSUE TITLE
Eve restarts mid missions - EVEProcessMemoryCeiling

### ISSUE THREAD

**Issue by Karr** [ISeeDEDPpl/Questor#89]
ISee: I don't know if it's just my end, but I noticed now that clients will restart mid mission.  Guessing EVEProcessMemoryCeiling 1150 EVEProcessMemoryCeiling might need a look at.  Noticed Clients restarting mid mission and using default profile from Eve InnerSpace when they restart.

This may be an InnerSpace update issue, need verification:

In the past, I would see memory hitting peak, then client would wait to finish mission, dock and then restart.  When it did restart, it would have restarted with the ISBoxer Character Set and not just the  EVE Online Default Profile.

So, what ended up happening was Instead of arranged windows, there were several windows on top of each other.  I would have to move them manually around the screen.

Running commit 3be0601b4f
from 5-17-2012

**Comment by ISeeDEDPpl** [comment]
Can you pm me the console logs that go along with that? 

specifically: 
Starting a timer in the innerspace uplink to restart this innerspace profile session
or
Starting a timer in the innerspace uplink to restart this isboxer character set

the restarting mid mission has been fixed locally. I will commit it tomorrow along with a few other fixes. The fact that you are restarting using the innerspace profile rather than the isboxer characterset  _seems_ to be your character setting xml. 

`
  <CloseQuestorCMDUplinkInnerspaceProfile>false</CloseQuestorCMDUplinkInnerspaceProfile>  
  <CloseQuestorCMDUplinkIsboxerCharacterSet>true</CloseQuestorCMDUplinkIsboxerCharacterSet>  
`

**Comment by ISeeDEDPpl** [comment]
This has been resolved in: 094d71756b89aca6ce5f32c552b2d462f0fb0e68

If you are still having issues with questor restarting using the 'wrong' method please double check your character settings xml and make sure you have the settings listed above correctly specified.
